@extends('layouts.app')
@section('title','Template details')
@section('content')
<section class="panel panel-pad"><h2 class="section-title">{{ $template->name }} · v{{ $template->version }}</h2><p><x-badge :status="$template->is_active?'Active':'Inactive'"/></p>
<p>{{ $used?'This version has initialized client accounts. Create a new version to change its definitions.':'This version has not initialized any client accounts. Its definitions can be edited.' }}</p>
<div class="actions"><a class="btn btn-outline-secondary" href="{{ route('account-templates.index') }}">All templates</a><a class="btn btn-outline-secondary" href="{{ route('account-templates.edit',$template) }}">Edit template</a>
@unless($used)<a class="btn btn-primary" href="{{ route('account-templates.items.create',$template) }}">Add item</a>@endunless
<form data-accounting-form method="post" action="{{ route('account-templates.version',$template) }}" data-confirm="Copy this template into a new inactive version? Existing client accounts will remain independent.">@csrf<button class="btn btn-outline-secondary">Create new version</button></form></div></section>
<section class="panel table-panel mt-3"><div class="table-responsive"><table class="table"><thead><tr><th>Code</th><th>Name</th><th>Classification</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($items as $item)<tr><td>{{ $item->code }}</td><td>{{ $item->name }}</td><td>{{ $item->classification }}</td><td><x-badge :status="$item->is_active?'Active':'Inactive'"/></td><td>@unless($used)<div class="actions"><a class="btn btn-sm btn-outline-secondary" href="{{ route('account-templates.items.edit',[$template,$item]) }}">Edit</a><form data-accounting-form method="post" action="{{ route('account-templates.items.destroy',[$template,$item]) }}" data-confirm="Remove this unused template item?">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Remove</button></form></div>@else Preserved @endunless</td></tr>@empty<tr><td colspan="5"><div class="empty-state"><h2>No account items</h2><p>Add account definitions before initializing a client chart.</p></div></td></tr>@endforelse</tbody></table></div></section><x-pagination :records="$items"/>
@endsection
