import assert from 'node:assert/strict';

export async function runJournal({ cdp, evaluate, fill, click, go, loaded, hasText, submit, shot, text, until }) {
  await cdp('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false });
  async function logout() {
    await click('form[action$="/logout"] button');
    await loaded('[name=email]');
  }
  async function login(email) {
    await fill('[name=email]', email); await fill('[name=password]', 'password123');
    await submit('form', 'SYNTHETIC BROWSER DEMO');
  }
  const change = selector => evaluate(`document.querySelector(${JSON.stringify(selector)}).dispatchEvent(new Event('change', { bubbles: true }))`);
  const input = selector => evaluate(`document.querySelector(${JSON.stringify(selector)}).dispatchEvent(new Event('input', { bubbles: true }))`);
  await logout(); await login('bookkeeper@veritascore.local');
  await go('/ledger/create', '[data-journal-form]');
  await fill('[name=client_id]', '1'); await change('[name=client_id]'); await hasText('Client options loaded.');
  const accounts1 = await evaluate(`[...document.querySelector('[name$="[account_id]"]').options].filter(o=>o.value).map(o=>({id:o.value,text:o.text}))`);
  const asset = accounts1.find(a => a.text.startsWith('001-SYN')).id;
  const revenue = accounts1.find(a => a.text.startsWith('002-SYN')).id;
  await fill('[name="items[0][account_id]"]', asset);
  await fill('[name=accounting_period_id]', await evaluate('document.querySelector("[name=accounting_period_id]").options[1].value'));
  await click('[name="document_ids[]"]');
  await fill('[name=client_id]', '2'); await change('[name=client_id]');
  await until(async () => await evaluate(`![...document.querySelector('[name$="[account_id]"]').options].some(o=>o.value===${JSON.stringify(asset)}) && document.querySelector('[name$="[account_id]"]').options.length>1`), 'second client options');
  assert.equal(await evaluate(`document.querySelector('[name$="[account_id]"]').value`), '');
  assert.equal(await evaluate('document.querySelector("[name=accounting_period_id]").value'), '');
  assert.equal(await evaluate(`document.querySelectorAll('[name="document_ids[]"]:checked').length`), 0);
  await fill('[name=client_id]', '1'); await change('[name=client_id]');
  await until(async () => await evaluate(`[...document.querySelector('[name$="[account_id]"]').options].some(o=>o.value===${JSON.stringify(asset)})`), 'first client options restored');
  await fill('[name=transaction_date]', '2026-04-12');
  await fill('[name=accounting_period_id]', await evaluate('document.querySelector("[name=accounting_period_id]").options[1].value'));
  await fill('[name=description]', 'SYNTHETIC Browser Journal');
  await fill('[name=reference_number]', 'SYNTHETIC-BROWSER-JOURNAL');
  await fill('[name="items[0][account_id]"]', asset); await fill('[name="items[0][debit]"]', '0.10');
  await fill('[name="items[1][account_id]"]', revenue); await fill('[name="items[1][credit]"]', '0.30');
  await click('[data-add-line]');
  assert.equal(await evaluate('document.querySelectorAll("[data-line-body] tr").length'), 3);
  assert.equal(await evaluate(`document.querySelector('[name="items[2][account_id]"]').value`), '');
  await fill('[name="items[2][account_id]"]', asset); await fill('[name="items[2][debit]"]', '0.20'); await input('[name="items[2][debit]"]');
  await hasText('Debit PHP 0.30 · Credit PHP 0.30 · Balanced');
  await click('[data-line-body] tr:last-child [data-remove-line]');
  assert.equal(await evaluate('document.querySelectorAll("[data-line-body] tr").length'), 2);
  await click('[data-add-line]');
  await fill('[name="items[2][account_id]"]', asset); await fill('[name="items[2][debit]"]', '0.20'); await input('[name="items[2][debit]"]');
  await click('[name="document_ids[]"]');
  await shot('journal-form-desktop');
  await cdp('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  await until(() => evaluate('document.querySelector("#sidebar").getBoundingClientRect().right <= 0'), 'mobile sidebar transition finished');
  console.log('Journal mobile layout:', await evaluate(`JSON.stringify({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,inner:innerWidth,overflow:[...document.querySelectorAll('main *')].filter(e=>e.getBoundingClientRect().right>390 && !e.closest('.table-responsive')).slice(0,12).map(e=>({tag:e.tagName,classes:e.className,width:e.getBoundingClientRect().width,right:e.getBoundingClientRect().right}))})`));
  await until(() => evaluate('document.documentElement.clientWidth === 390 && document.documentElement.scrollWidth <= 390'), 'journal layout fits the 390px device width');
  await shot('journal-form-mobile');
  assert.equal(await evaluate('document.documentElement.scrollWidth <= document.documentElement.clientWidth'), true, 'Journal page must not overflow on mobile');
  await submit('[data-journal-form]', 'Transaction created successfully.');
  const entryUrl = await evaluate('location.pathname');
  await hasText('Download retained synthetic-browser.pdf');
  await click('a[data-modal]'); await loaded('#formModal [data-journal-form]');
  assert.equal(await evaluate('document.querySelectorAll("#formModal [data-line-body] tr").length'), 3);
  await click('#formModal [data-add-line]');
  assert.equal(await evaluate(`document.querySelector('#formModal [name="items[3][id]"]').value`), '', 'Cloned line must not copy the saved line ID');
  await click('#formModal [data-line-body] tr:last-child [data-remove-line]');
  await submit('#formModal [data-journal-form]', 'Record updated successfully.');
  await click('form:has([name=action][value=submit]) button'); await hasText('Journal workflow updated.');
  assert.ok((await text()).includes('For Review'));
  assert.ok(!(await text()).includes('Approve review'));
  await logout(); await login('manager@veritascore.local');
  await go(entryUrl); await click('button[name=action][value=review]'); await hasText('Journal workflow updated.');
  assert.ok((await text()).includes('Reviewed by'));
  await shot('journal-reviewed');
  await click('button[name=action][value=return]'); await until(async () => (await text()).includes('Needs Correction'), 'correction state');
  assert.ok(!(await text()).includes('Reviewed by'));
  await logout(); await login('bookkeeper@veritascore.local');
  await go(entryUrl); await click('form:has([name=action][value=submit]) button'); await hasText('Journal workflow updated.');
  await logout(); await login('manager@veritascore.local');
  await go(entryUrl); await click('button[name=action][value=review]'); await hasText('Post journal'); await loaded('form[action$="/post"]');
  await click('form[action$="/post"] button');
  await until(() => evaluate('document.querySelector("#confirmModal").classList.contains("show")'), 'posting confirmation');
  await shot('journal-post-confirm-mobile');
  await click('#confirmAccept'); await hasText('Journal posted successfully.'); await loaded('main');
  await hasText('Posted by Sample Office Manager');
  assert.ok(!(await text()).includes('Return for correction'));
  assert.equal(await evaluate(`document.querySelectorAll('form[action$="/post"], a[data-modal]').length`), 0);
  await until(() => evaluate('document.documentElement.clientWidth === 390 && document.documentElement.scrollWidth <= 390'), 'posted journal fits mobile');
  await shot('journal-posted-mobile');
  await cdp('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false });
  await shot('journal-posted-desktop');
  console.log('PASS: Confirmed Manager posting, posting actor/time, immutable detail page, audit visibility, desktop/mobile posting views.');
  console.log('PASS: Journal client-dependent selections, selection clearing, add/remove/reindex including modal edit, exact 0.10 + 0.20 totals, optional evidence, Bookkeeper submission, independent Manager review, correction invalidation, desktop/mobile layout.');
}
