@extends('layouts.app')
@section('title','Overview')
@section('content')<section class="hero"><div class="eyebrow">A CLEARER VIEW OF YOUR PRACTICE</div><h2 class="hero-title">Welcome back, {{ auth()->user()->name }}.</h2><div class="hero-date">{{ now()->format('l, F j, Y') }}</div><p class="hero-summary">{{ $stats['overdue'] }} overdue filings need attention. {{ $stats['upcoming'] }} more deadlines are approaching in the next 10 days.</p><div class="hero-bottom"><span class="hero-note"><i class="bi bi-shield-check" aria-hidden="true"></i>One workspace. Every detail accounted for.</span><a class="btn btn-primary" href="{{ route('compliance.index') }}">Review deadlines ↗</a></div></section>
<div class="toolbar"><h2 class="section-title">{{ $role }} overview</h2><div class="actions"><a data-modal class="btn btn-sm btn-outline-secondary" href="{{ route('clients.create') }}">New client</a><a data-modal class="btn btn-sm btn-outline-secondary" href="{{ route('documents.create') }}">Add document</a><a data-modal class="btn btn-sm btn-outline-secondary" href="{{ route('billing.create') }}">New invoice</a></div></div>
<div class="row g-3 mb-4">@if($userCount!==null)<x-stat label="User accounts" :value="$userCount" icon="people-fill"/>@endif @if($noticeCount!==null)<x-stat label="Published notices" :value="$noticeCount" icon="megaphone"/>@endif</div>
<div class="actions mb-4">@can('document.validate')<a class="btn btn-outline-secondary" href="{{ route('documents.index',['status'=>'Submitted']) }}">Documents for validation</a>@endcan @can('bookkeeping.create')<a class="btn btn-outline-secondary" href="{{ route('ledger.create') }}">New bookkeeping entry</a>@endcan @can('bookkeeping.review')<a class="btn btn-outline-secondary" href="{{ route('ledger.index',['status'=>'For Review']) }}">Bookkeeping review queue</a>@endcan @can('notice.view')<a class="btn btn-outline-secondary" href="{{ route('notices.index') }}">Notices</a>@endcan</div>
<div class="row g-3 mb-4"><x-stat :label="auth()->user()->hasRole('bookkeeper')?'Assigned active clients':'Active clients'" :value="$stats['active']" :note="$stats['clients'].' total · '.$stats['new'].' new this month'" icon="people"/><x-stat label="Documents in progress" :value="$stats['pending']+$stats['review']+$stats['clarification']" :note="$stats['clarification'].' need clarification'" icon="folder2-open"/><x-stat label="Due within 10 days" :value="$stats['upcoming']" note="Prepare early" icon="calendar2-week" tone="warning"/><x-stat label="Overdue filings" :value="$stats['overdue']" note="Follow-up required" icon="exclamation-circle" :tone="$stats['overdue']?'danger':'success'"/></div>
<div class="row g-3 mb-4"><div class="col-xl-8"><section class="panel table-panel"><div class="panel-heading"><div><h2 class="section-title">Compliance watch</h2><p class="section-description">Nearest unresolved filings</p></div><a class="btn btn-sm btn-outline-secondary" href="{{ route('compliance.index') }}">View all</a></div><div class="table-responsive"><table class="table"><thead><tr><th>Client & requirement</th><th>Agency</th><th>Due date</th><th>Status</th></tr></thead><tbody>@forelse($deadlines as $item)<tr><td><a href="{{ route('compliance.show',$item) }}">{{ $item->requirement }}</a><div class="subtext">{{ $item->client->business_name }}</div></td><td>{{ $item->agency }}</td><td>{{ $item->due_date->format('M j, Y') }}</td><td><x-badge :status="$item->urgency"/></td></tr>@empty<tr><td colspan="4"><div class="empty-state"><h3>No open deadlines</h3><p>Your filing queue is clear.</p>@can('create',\App\Models\ComplianceRecord::class)<a data-modal class="btn btn-primary" href="{{ route('compliance.create') }}">Add deadline</a>@endcan</div></td></tr>@endforelse</tbody></table></div></section></div>
<div class="col-xl-4"><section class="panel panel-pad"><h2 class="section-title">Billing snapshot</h2><div class="billing-total">{{ \App\Support\Money::format($stats['billing']['outstanding']) }}</div><p class="subtext">Outstanding balance</p><div class="metric-label"><span>Invoices paid</span><span>{{ $stats['billing']['paid'] }} paid · {{ $stats['billing']['open'] }} open</span></div><progress class="metric-progress" aria-label="Invoices paid" value="{{ $stats['billing']['paid'] }}" max="{{ max(1,$stats['billing']['paid']+$stats['billing']['open']) }}"></progress><p class="subtext mt-4">Collected: {{ \App\Support\Money::format($stats['billing']['collected']) }}<br>Total billed: {{ \App\Support\Money::format($stats['billing']['billed']) }}<br>Overdue: {{ \App\Support\Money::format($stats['billing']['overdue']) }}</p><a class="btn btn-sm btn-outline-secondary" href="{{ route('billing.index') }}">Open billing</a></section></div></div>
<div class="row g-3 mb-4"><x-stat label="Submitted documents" :value="$stats['pending']" icon="file-earmark"/><x-stat label="Documents under review" :value="$stats['review']" icon="file-earmark-check"/><x-stat label="Need clarification" :value="$stats['clarification']" icon="question-circle" tone="warning"/><x-stat label="Ledger entries for review" :value="$stats['ledger']" icon="journal-text"/></div>
<div class="row g-3">@foreach(['Recent clients'=>['clients',$clients,'business_name'],'Recent documents'=>['documents',$documents,'title'],'Recent invoices'=>['billing',$invoices,'invoice_number']] as $label=>$group)<div class="col-lg-4"><section class="panel panel-pad"><h2 class="section-title">{{ $label }}</h2><ul class="timeline">@forelse($group[1] as $item)<li><div class="timeline-content"><a href="{{ route($group[0].'.show',$item) }}">{{ $item->{$group[2]} }}</a><div class="subtext">{{ $item->created_at->format('M j, Y') }}</div></div><x-badge :status="$item->display_status??$item->status"/></li>@empty<li>No records yet.</li>@endforelse</ul></section></div>@endforeach</div>
<section class="panel panel-pad mt-4"><h2 class="section-title">Recent activity</h2><ul class="timeline">@forelse($activity as $item)<li><i class="bi bi-clock-history" aria-hidden="true"></i><div class="timeline-content">{{ $item->description }}<div class="subtext">{{ $item->user?->name }} · {{ $item->created_at->format('M j, g:i A') }}</div></div></li>@empty<li>Your activity will appear as records are saved.</li>@endforelse</ul></section>@endsection
