<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\AccountTemplateController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ComplianceController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\FinancialReportController;
use App\Http\Controllers\FollowUpController;
use App\Http\Controllers\GeneralLedgerController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\KnowledgeController;
use App\Http\Controllers\LedgerController;
use App\Http\Controllers\MissingDocumentsController;
use App\Http\Controllers\NoticeController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RequirementController;
use App\Http\Controllers\RequirementTemplateController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VoucherController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/dashboard');
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login', [AuthController::class, 'authenticate'])->middleware('throttle:10,1')->name('login.store');
    Route::get('/forgot-password', [AuthController::class, 'forgot'])->name('password.request');
    Route::post('/forgot-password', [AuthController::class, 'email'])->middleware('throttle:5,1')->name('password.email');
    Route::get('/reset-password/{token}', [AuthController::class, 'resetForm'])->name('password.reset');
    Route::post('/reset-password', [AuthController::class, 'reset'])->middleware('throttle:5,1')->name('password.update');
});
Route::middleware(['auth', 'active', 'role:owner,bookkeeper,office-manager'])->group(function () {
    Route::get('/vouchers/{voucher}/print', [VoucherController::class, 'print'])->name('vouchers.print');
    Route::resource('vouchers', VoucherController::class)->except('destroy');
    Route::get('/financial-reports', [FinancialReportController::class, 'index'])->name('financial-reports.index');
    Route::get('/financial-reports/print', [FinancialReportController::class, 'print'])->name('financial-reports.print');
    Route::get('/general-ledger', [GeneralLedgerController::class, 'index'])->name('general-ledger.index');
    Route::get('/general-ledger/print', [GeneralLedgerController::class, 'print'])->name('general-ledger.print');
    Route::get('/accounts/initialize', [AccountController::class, 'initialization'])->name('accounts.initialization');
    Route::post('/accounts/initialize', [AccountController::class, 'initialize'])->name('accounts.initialize');
    Route::post('/accounts/{account}/status', [AccountController::class, 'status'])->name('accounts.status');
    Route::resource('accounts', AccountController::class)->except('destroy');
    Route::post('/account-templates/{accountTemplate}/version', [AccountTemplateController::class, 'version'])->name('account-templates.version');
    Route::get('/account-templates/{accountTemplate}/items/create', [AccountTemplateController::class, 'createItem'])->name('account-templates.items.create');
    Route::post('/account-templates/{accountTemplate}/items', [AccountTemplateController::class, 'storeItem'])->name('account-templates.items.store');
    Route::get('/account-templates/{accountTemplate}/items/{item}/edit', [AccountTemplateController::class, 'editItem'])->name('account-templates.items.edit');
    Route::put('/account-templates/{accountTemplate}/items/{item}', [AccountTemplateController::class, 'updateItem'])->name('account-templates.items.update');
    Route::delete('/account-templates/{accountTemplate}/items/{item}', [AccountTemplateController::class, 'destroyItem'])->name('account-templates.items.destroy');
    Route::resource('account-templates', AccountTemplateController::class)->parameters(['account-templates' => 'accountTemplate'])->except('destroy');
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/profile', [AuthController::class, 'profile'])->name('profile.edit');
    Route::patch('/profile', [AuthController::class, 'updateProfile'])->name('profile.update');
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::post('/clients/{record}/archive', [ClientController::class, 'archive'])->name('clients.archive');
    Route::get('/documents/{record}/validate', [DocumentController::class, 'validation'])->middleware('permission:document.validate')->name('documents.validation');
    Route::post('/documents/{record}/validate', [DocumentController::class, 'validateDocument'])->middleware('permission:document.validate')->name('documents.validate');
    Route::get('/documents/{record}/download', [DocumentController::class, 'download'])->name('documents.download');
    Route::get('/requirements/monitoring', [MissingDocumentsController::class, 'index'])->name('requirements.monitoring');
    Route::get('/requirements/templates', [RequirementTemplateController::class, 'index'])->name('requirements.templates.index');
    Route::post('/requirements/templates', [RequirementTemplateController::class, 'store'])->name('requirements.templates.store');
    Route::put('/requirements/templates/{template}', [RequirementTemplateController::class, 'update'])->name('requirements.templates.update');
    Route::delete('/requirements/templates/{template}', [RequirementTemplateController::class, 'destroy'])->name('requirements.templates.destroy');
    Route::post('/requirements/templates/{template}/apply', [RequirementTemplateController::class, 'apply'])->name('requirements.templates.apply');
    Route::get('/requirements/create', [RequirementController::class, 'create'])->name('requirements.create');
    Route::post('/requirements', [RequirementController::class, 'store'])->name('requirements.store');
    Route::get('/requirements', [RequirementController::class, 'index'])->name('requirements.index');
    Route::get('/clients/{client}/checklist', [RequirementController::class, 'checklist'])->name('requirements.checklist');
    Route::get('/requirements/{requirement}/edit', [RequirementController::class, 'edit'])->name('requirements.edit');
    Route::put('/requirements/{requirement}', [RequirementController::class, 'update'])->name('requirements.update');
    Route::delete('/requirements/{requirement}', [RequirementController::class, 'destroy'])->name('requirements.destroy');
    Route::post('/requirements/{requirement}/toggle', [RequirementController::class, 'toggle'])->name('requirements.toggle');
    Route::post('/requirements/{requirement}/link', [RequirementController::class, 'link'])->name('requirements.link');
    Route::delete('/requirements/{requirement}/documents/{document}', [RequirementController::class, 'unlink'])->name('requirements.unlink');
    Route::post('/requirements/{requirement}/follow-ups', [FollowUpController::class, 'store'])->name('requirements.follow-ups.store');
    Route::put('/follow-ups/{followUp}', [FollowUpController::class, 'update'])->name('follow-ups.update');
    Route::delete('/follow-ups/{followUp}', [FollowUpController::class, 'destroy'])->name('follow-ups.destroy');
    Route::post('/ledger/{record}/post', [LedgerController::class, 'post'])->name('ledger.post');
    Route::post('/ledger/{record}/transition', [LedgerController::class, 'transition'])->name('ledger.transition');
    Route::get('/ledger/options', [LedgerController::class, 'options'])->name('ledger.options');
    Route::get('/ledger/{record}/evidence/{evidence}', [LedgerController::class, 'evidence'])->name('ledger.evidence');
    Route::post('/billing/{record}/transition', [InvoiceController::class, 'transition'])->name('billing.transition');
    Route::post('/billing/{record}/payments', [PaymentController::class, 'store'])->name('billing.payments.store');
    Route::get('/billing/{record}/print', [InvoiceController::class, 'print'])->name('billing.print');
    Route::get('/billing/{record}/pdf', [InvoiceController::class, 'pdf'])->name('billing.pdf');
    Route::get('/compliance/monitoring', [ComplianceController::class, 'monitor'])->name('compliance.monitoring');
    Route::get('/clients/{client}/compliance', [ComplianceController::class, 'checklist'])->name('compliance.checklist');
    Route::post('/compliance/{record}/follow-ups', [ComplianceController::class, 'storeFollowUp'])->name('compliance.follow-ups.store');
    Route::put('/compliance-follow-ups/{followUp}', [ComplianceController::class, 'updateFollowUp'])->name('compliance.follow-ups.update');
    Route::delete('/compliance-follow-ups/{followUp}', [ComplianceController::class, 'destroyFollowUp'])->name('compliance.follow-ups.destroy');
    foreach (['clients' => ClientController::class, 'documents' => DocumentController::class, 'ledger' => LedgerController::class, 'compliance' => ComplianceController::class, 'billing' => InvoiceController::class, 'knowledge' => KnowledgeController::class] as $module => $controller) {
        Route::resource($module, $controller)->parameters([$module => 'record'])->except($module === 'billing' ? ['destroy'] : []);
    }
    Route::get('/search', SearchController::class)->middleware('throttle:90,1')->name('search');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
    Route::post('/notifications/read-all', [NotificationController::class, 'all'])->name('notifications.all');
    Route::post('/notifications/{id}/read', [NotificationController::class, 'read'])->name('notifications.read');
    Route::get('/reports', [ReportController::class, 'index'])->middleware('permission:report.view,report.generate')->name('reports.index');
    Route::get('/reports/csv', [ReportController::class, 'csv'])->middleware('permission:report.export')->name('reports.csv');
    Route::middleware('permission:notice.view')->group(function () {
        Route::post('/notices/{notice}/publish', [NoticeController::class, 'publish'])->name('notices.publish');
        Route::post('/notices/{notice}/archive', [NoticeController::class, 'archive'])->name('notices.archive');
        Route::resource('notices', NoticeController::class)->except('destroy');
    });
    Route::middleware('role:owner')->group(function () {
        Route::get('/workspace', [SettingController::class, 'edit'])->middleware('permission:workspace.manage')->name('workspace.edit');
        Route::put('/workspace', [SettingController::class, 'update'])->middleware('permission:workspace.manage')->name('workspace.update');
        Route::resource('admin/users', UserController::class)->names('admin.users')->except(['show', 'destroy']);
        Route::post('/admin/users/{user}/reset-password', [UserController::class, 'reset'])->name('admin.users.reset');
        Route::get('/admin/audit-logs', [AuditLogController::class, 'index'])->middleware('permission:audit.view')->name('admin.audit.index');
    });
});
