@include('billing.items')
<div class="mini-stats"><div class="mini-stat"><strong>{{ \App\Support\Money::format($record->total_amount) }}</strong><span>Total invoice</span></div><div class="mini-stat"><strong>{{ \App\Support\Money::format($record->amount_paid) }}</strong><span>Paid</span></div><div class="mini-stat"><strong>{{ \App\Support\Money::format($record->balance) }}</strong><span>Balance</span></div></div>
<div class="actions mb-4"><a target="_blank" rel="noopener" class="btn btn-outline-secondary" href="{{ route('billing.print',$record) }}">Print invoice</a><a class="btn btn-outline-secondary" href="{{ route('billing.pdf',$record) }}">Download PDF</a>
@can('issue',$record)<form method="post" action="{{ route('billing.transition',$record) }}">@csrf<input type="hidden" name="action" value="issue"><button class="btn btn-primary">Issue invoice</button></form>@endcan
@can('cancel',$record)@if($record->status!=='Cancelled' && !$record->payments()->exists())<form method="post" action="{{ route('billing.transition',$record) }}" data-confirm="Cancel this invoice? This action cannot be reversed.">@csrf<input type="hidden" name="action" value="cancel"><button class="btn btn-outline-danger">Cancel invoice</button></form>@endif
@endcan</div>
<h3 class="section-title">Payment history</h3><div class="table-responsive mb-4"><table class="table"><thead><tr><th>Date</th><th>Method</th><th>Reference</th><th>Recorded by</th><th class="numeric">Amount</th></tr></thead><tbody>@forelse($record->payments()->with('recorder')->latest()->get() as $payment)<tr><td>{{ $payment->payment_date->format('M j, Y') }}</td><td>{{ $payment->payment_method }}</td><td>{{ $payment->reference_number }}</td><td>{{ $payment->recorder?->name }}</td><td class="numeric">{{ \App\Support\Money::format($payment->amount) }}</td></tr>@empty<tr><td colspan="5">No payments recorded.</td></tr>@endforelse</tbody></table></div>
@can('recordPayment',$record)@if($record->status==='Open' && $record->balance_cents>0)<h3 class="section-title mb-3">Record payment</h3><form method="post" action="{{ route('billing.payments.store',$record) }}">@csrf<div class="row"><div class="col-md-4"><x-field name="payment_date" label="Payment date" type="date" :value="today()->toDateString()" :required="true"/></div><div class="col-md-4"><x-field name="amount" label="Amount (PHP)" type="number" :required="true"/></div><div class="col-md-4"><x-field name="payment_method" label="Method" type="select" :options="array_combine(['Cash','Bank Transfer','Cheque','GCash','Other'],['Cash','Bank Transfer','Cheque','GCash','Other'])" :required="true"/></div><div class="col-md-6"><x-field name="reference_number" label="Payment reference"/></div><div class="col-md-6"><x-field name="notes" label="Notes"/></div></div><button class="btn btn-primary">Record payment</button></form>@endif
@endcan
